apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpadeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hpaapp
  template:
    metadata:
      name: hpappod
      labels:
        app: hpaapp
    spec:
      containers:
      - name: hpacontainer
        image: k8s.gcr.io/hpa-example
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: 64Mi
          limits:
            cpu: "100m"
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hpaservice
spec:
  type: NodePort
  selector:
    app: hpaapp
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpadeploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpadeployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 50
      type: Resource
