apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mavenwebappds
spec:
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcontainer
        image: vijay3460/maven-web-app:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappdssvc
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
