apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-vol1
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.219
    path: /mnt/share
  capacity:
    storage: 1Gi
