apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-vol2
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.219
    path: /mnt/share
  capacity:
    storage: 500Mi
