apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  capacity:
    storage: 500Mi
  nfs:
    server: 192.168.1.219
    path: /mnt/share
